version: '3.7'

services:
  database:
    container_name: diplomDB
    image: 'postgres'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  diplom:
    container_name: diplomAPP
    image: 'app'
    build:
      context: .
    ports:
      - 8085:8085